Jenya workflow
cpp-park-vk-education/2022_2_Teiko pull request #1
Opened 2022-10-26 21:28 UTC by UjinIaly

fir

2022-10-29 19:19 UTC, rkhazh requested changes

2022-10-29 19:19 UTC, rkhazh commented on .idea/.gitignore
> +# Default ignored files
Эта папка точно должна быть тут?

2022-10-29 19:19 UTC, rkhazh commented on .github/workflows/main.yml
> +      - run: cmake . &&  cmake --build . &&  CTEST_OUTPUT_ON_FAILURE=TRUE cmake --build . --target test
Нужно пользоваться артефактами, загруженными в прошлой джобе. И разделите строку. Слишком длинная

2022-10-29 19:19 UTC, rkhazh commented on .github/workflows/main.yml
> +jobs:
CI падает

2022-10-29 19:19 UTC, rkhazh commented on CMakeLists.txt
> +add_executable(2022_2_Teiko modules/main.cpp modules/main.h tests/test.cpp)
Исходники в отдельную переменную

2022-10-29 19:19 UTC, rkhazh commented on CMakeLists.txt
> +        COMMAND tests)
\n в конце каждого файла. Почитайте, почему это важно

2022-10-29 19:19 UTC, rkhazh commented on CMakeLists.txt
> +        COMMAND tests)
Декомпозируйте. Тесты в отдельную директорию, там же отдельный cmake, который потом подключается через add_subdirectory

2022-10-29 19:19 UTC, rkhazh commented on Dockerfile
> +COPY cpplint.py .
Возможно стоит внутри докера клонить актуальную репу

2022-10-29 19:19 UTC, rkhazh commented on Makefile
> +	echo "Testing"
Забавно

2022-10-29 19:19 UTC, rkhazh commented on Makefile
> +check:
.PHONY забыли указать

2022-10-29 19:19 UTC, rkhazh commented on cmake-build-debug/.cmake/api/v1/reply/directory-.-Debug-f5ebdc15457944623624.json
> +{
Эта папка тоже тут не должна быть

2022-10-29 19:19 UTC, rkhazh commented on tests/test.cpp
> +#include "../modules/main.h"
Добавьте пару тестов. Они должны в CI запускаться

2022-11-06 18:02 UTC, rkhazh approved these changes
Все ок, молодцы

2022-11-06 18:02 UTC, rkhazh commented on CMakeLists.txt
> +add_library(hello SHARED ${PROJECT_SRCS})
\n

2022-11-11 12:30 UTC, Keberson commented
Добавил символ переноса строки в конце файла

2022-11-21 09:28 UTC, closed without merging

2022-12-22 10:11 UTC, vozvivan commented on cpplint.py
> +#!/usr/bin/env python
даже если добавляешь, хорошо бы это спрятать, например, в скрытую папку

2022-12-22 10:11 UTC, vozvivan commented on Dockerfile
> +COPY ./src ./src
а нельзя было одноу командой?

2022-12-22 10:11 UTC, vozvivan commented on Dockerfile
> +RUN apt update -y && \
сознательно разбил на два слоя? почему?

2022-12-22 10:11 UTC, vozvivan commented on Dockerfile
> +FROM gcc:latest
лучше фиксировать, а не брать latest

2022-12-22 10:11 UTC, vozvivan commented on Dockerfile
> +RUN cmake . && \
это точно ожидаемое поведение? что мы прим при старте докера все билдим

2022-12-22 10:11 UTC, vozvivan commented on src/hello.cpp
> +#include "../include/hello.h"
хорошо бы без относительных путей

2022-12-22 10:11 UTC, vozvivan commented on .github/workflows/main.yml
> +  test:
хорошо бы еще покрытие добавить

2022-12-22 10:11 UTC, vozvivan commented on tests/test.cpp
> +#include <iostream>
для чего?